name: Build scripts
on:
  # Note: Cannot run this on pushes / pull requests as no (default) inputs can be
  # defined there. Need to trigger this manually via workflow_dispatch.
  #push:
  #  branches:
  #    - '**'
  #  tags-ignore:
  #    - '**'
  #pull_request:

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
    inputs:
      additional-packages:
        description: Space-separated list of additional operating system packages to install.
        required: false
        default: ''
        type: string
      testrunner-include-optional-dependencies:
        description: Flag whether to also clone and include in PATH dependencies marked as optional.
        required: false
        default: false
        type: boolean
      testrunner-settings:
        description: Additional environment settings (in the form VAR=VALUE) to pass to the test runner.
        required: false
        default: ''
        type: string
      testrunner-submodules:
        description: Flag whether to check out submodules.
        required: false
        default: false
        type: boolean

  # Allows reuse of this workflow as a generic build for my scripting projects.
  workflow_call:
    inputs:
      additional-packages:
        description: Space-separated list of additional operating system packages to install.
        required: false
        default: ''
        type: string
      testrunner-include-optional-dependencies:
        description: Flag whether to also clone and include in PATH dependencies marked as optional.
        required: false
        default: false
        type: boolean
      testrunner-settings:
        description: Additional environment settings (in the form VAR=VALUE) to pass to the test runner.
        required: false
        default: ''
        type: string
      testrunner-submodules:
        description: Flag whether to check out submodules.
        required: false
        default: false
        type: boolean

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Bats
        run: |
          sudo apt-get update --yes
          sudo apt-get install --yes bats bats-assert bats-file ${{ inputs.additional-packages }}
      - name: Run tests
        uses: inkarkat/scripting-testrunner@master
        with:
          include-optional-dependencies: ${{ inputs.testrunner-include-optional-dependencies }}
          settings: ${{ inputs.testrunner-settings }}
          submodules: ${{ inputs.testrunner-submodules }}
