name: Build scripts
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
  # Allows reuse of this workflow as a generic build for my scripting projects.
  workflow_call:
    inputs:
      additional-packages:
        description: Space-separated list of additional operating system packages to install.
        required: false
        default: ''
        type: string

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Bats
        run: |
          sudo apt-get update --yes
          sudo apt-get install --yes bats bats-assert bats-file ${{ inputs.additional-packages }}
      - name: Run tests
        uses: inkarkat/scripting-testrunner@master
